# https://help.github.com/articles/customizing-css-and-html-in-your-jekyll-theme/

theme: jekyll-theme-cayman

# https://github.com/pages-themes/cayman/blob/master/_layouts/default.html
title: Research and Development on Unified Environment of Accelerated Computing and Interconnection for Post-Petascale Era

github:
  is_project_page: false
