# https://help.github.com/articles/customizing-css-and-html-in-your-jekyll-theme/

theme: jekyll-theme-cayman

# https://github.com/pages-themes/cayman/blob/master/_layouts/default.html
title: Advanced Computing & Optimization Infrastructure for Extremely Large-Scale Graphs on Post Peta-Scale Supercomputers

github:
  is_project_page: false
